version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - WEBHOOK_URL=http://95.216.208.87:5678/
      - N8N_SECURE_COOKIE=false
    restart: always
    volumes:
      - ~/.n8n:/home/node/.n8n
