version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Rome
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecure
      - N8N_HOST=n8n-gpt-backup.lukeserver.ai
      - WEBHOOK_TUNNEL_URL=https://n8n-gpt-backup.lukeserver.ai
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped
