services:
  - type: web
    name: drop-drive-auth
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars:
      - key: CLIENT_SECRET_FILE
        value: client_secret.json
      - key: TOKEN_FILE
        value: token.json
      - key: REDIRECT_URI
        value: https://drop-drive-auth.onrender.com/auth/callback
      - key: BACKUP_SOURCE
        value: output/
      - key: GDRIVE_FOLDER_ID
        value: 16ilWwbaFk6Zj0ssInwPImYCzz_9b0BXC

  - type: cron
    name: backup-every-3h
    env: python
    schedule: '0 */3 * * *'
    buildCommand: pip install -r requirements.txt
    startCommand: python backup.py
    envVars:
      - key: CLIENT_SECRET_FILE
        value: client_secret.json
      - key: TOKEN_FILE
        value: token.json
      - key: BACKUP_SOURCE
        value: output/
      - key: GDRIVE_FOLDER_ID
        value: 16ilWwbaFk6Zj0ssInwPImYCzz_9b0BXC
