# render.yaml - Configurazione servizio Render per upload agenti
services:
  - type: worker
    name: upload-saas-agent
    env: python
    region: frankfurt
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python upload_agent_files.py"
    envVars:
      - key: GDRIVE_FOLDER_ID
        value: 16ilWwbaFk6Zj0ssInwPImYCzz_9b0BXC
      - key: TOKEN_FILE
        value: token.json
