services:
  - type: web
    name: drop-drive-backup
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"  # 🔥 Qui c'è l'errore
    envVars:
      - key: CLIENT_SECRET_FILE
        value: client_secret.json
      - key: TOKEN_FILE
        value: token.json
      - key: REDIRECT_URI
        value: https://drop-drive-backup.onrender.com/auth/callback
      - key: BACKUP_SOURCE
        value: output/
      - key: GDRIVE_FOLDER_ID
        value: 1ewRXIwPs-gxmtfn6S0z95LYk9yrZxgwL
      - key: OAUTHLIB_INSECURE_TRANSPORT
        value: 1
